### ISSUE TITLE
not able to use @import url("something.css");

### ISSUE THREAD

**Issue by ShyamRaj** [aaronj1335/webpack-postcss-tools#11]
During webpack compilation it throws the following `Error: Cannot find module 'url("something.css")'`

**Comment by aaronj1335** [comment]
Hi Shyam! Unless I can see your project directory, there's not a lot I can do to help debug. A few possibilities:
- You need to configure WebPack to resolve CSS files as modules ([example](https://github.com/aaronj1335/webpack-postcss-tools/blob/a04dc1e8d321a24d754d24f31a4d14d543d1c4c4/examples/one-link-element/webpack.config.js#L22))
- WebPack is trying to resolve `something.css` similarly to how Node.js resolves `require()` calls, so it thinks `someting.css` is the module name, but you're trying to reference a file in your project. If this is the case, prepend a `./`: `url("./something.css")`.
- You just don't have a `something.css`, module, file, or otherwise.

Feel free to link to an archive of your project. Otherwise, please check out [the examples directory](https://github.com/aaronj1335/webpack-postcss-tools/tree/a04dc1e8d321a24d754d24f31a4d14d543d1c4c4/examples).
