### ISSUE TITLE
Add option to use alternative variable syntax

### ISSUE THREAD

**Issue by iest** [aaronj1335/webpack-postcss-tools#6]
It's not immediately clear that this module only supports the W3C (`--myVariable`) style syntax. It would be cool to be able to pass in a variable matcher — for example to support [sass-style variable syntax](https://github.com/postcss/postcss-simple-vars) (if, like me, you hate the W3C syntax).

**Comment by aaronj1335** [comment]
please take a through [the examples directory](https://github.com/aaronj1335/webpack-postcss-tools/tree/master/examples), where you can see [the w3c-style variables being used](https://github.com/aaronj1335/webpack-postcss-tools/blob/4a4ee477a48873987a2bd7004958eda94efa6e02/examples/one-link-element/src/main/index.css#L4).

the only api for this that i can come up with right now that i'd be comfortable introducing is exporting another function like `makeSimpleVarMap` which could generate the variables to be passed into the postcss/postcss-simple-vars plugin. if you'd want to implement this along with the requisite tests and the code stays clean i'd consider merging it

i'm also open to discussing other api's, though since this is a corner case, i'm going to be strict about increasing the api footprint for it.

**Comment by aaronj1335** [comment]
closing since i haven't heard anything back for a bit.

**Comment by iest** [comment]
Apologies @aaronj1335 I missed the update back in May! I'm now using the w3c-proposed syntax so have no issue. Thanks for following up.

**Comment by aaronj1335** [comment]
👍🏼
