### ISSUE TITLE
prependTildesToImports no longer works with css-loader v0.15.4

### ISSUE THREAD

**Issue by dtothefp** [aaronj1335/webpack-postcss-tools#7]
Not sure if you are still maintaining this repo, but looks like updates to `css-loader` are happening quickly with ability to local scope CSS modules. `prependTildesToImports` now results in `@imported` modules not being found. You can see an example in this branch https://github.com/dtothefp/postcss-webpack-suitcss/tree/dfp/update-css-loader. Master contains the old version and works fine whereas the branch results in the following error.

<img width="423" alt="screen shot 2015-07-17 at 3 19 06 pm" src="https://cloud.githubusercontent.com/assets/4656726/8755224/3688321e-2c97-11e5-8e4d-e3d072047c03.png">

**Comment by aaronj1335** [comment]
still maintaining, just not using in my day-to-day work, so i really appreciate the heads up.

i'll take a look when i've got some more time, but it looks like i may need to scope the `prependTildesToImports` usage to everything <=0.15.4, and then release a new version that doesn't use it.

**Comment by dtothefp** [comment]
@aaronj1335 thanks for the reply. I was a little confused on what this is accomplishing and if it is even necessary with updated versions of the `css-loader`?

**Comment by aaronj1335** [comment]
yes, in previous versions of `css-loader`, `@import 'foo';` would look up `foo` as a relative path, rather than a module (i.e. `./foo` instead of `node_modules/foo/index.css`). `prependTildesToImports` would use postcss to rewrite imports like that to `@import '~foo'`, so that webpack would look up `foo` as a module. this was important because libraries like suit css just have the regular import statements, and it wouldn't make sense to change them to match webpack's quirks.

so if this is fixed in newer versions of `css-loader`, than the only thing you might need from this package is the `makeVarMap` function, which enables sharing css variables across different modules. though even that may be better implemented by just waiting until the css is concatenated to do variable resolution. either way, the big change to the examples would just be removing [the `prependTildesToImports` calls](https://github.com/aaronj1335/webpack-postcss-tools/blob/4a4ee477a48873987a2bd7004958eda94efa6e02/examples/one-link-element/webpack.config.js#L36).

**Comment by aaronj1335** [comment]
sorry for the delay here, but i've looked into it more, and i think `prependTildesToImports` is just not compatible with `?modules`. if you're using `?modules` though, you probably don't need this function since `css-modules` takes care of module resolution.

regardless, `prependTildesToImports` is still useful in some cases. since `css-modules` makes the class names available in the javascript, they can actually make the JS file larger. additionally, in my testing `css-loader?modules!postcss-loader` did not apply the postcss transforms to transitive css dependencies. that means if you're using the above loader with something like basscss, the library is included without being processed by postcss.
